### ISSUE TITLE
queries with pagination fails with `iterator is invalid`

### ISSUE THREAD

**Issue by aleem1314** [regen-network/regen-ledger#1113]
## Summary of Bug

When querying ecocredit batches with `pagination.limit=1` and `pagination.count_total=true` queries is throwing invalid iterator error.

## Version

master

## Steps to Reproduce

Here is a test case to reproduce

```
func TestQuery_Batches(t *testing.T) {
	t.Parallel()
	s := setupBase(t)

	// insert project
	pKey, err := s.stateStore.ProjectTable().InsertReturningID(s.ctx, &api.Project{
		Id: "C01-001",
	})
	assert.NilError(t, err)

	batch := &api.Batch{
		ProjectKey: pKey,
		Denom:      "C01-20200101-20220101-001",
		Metadata:   "",
		StartDate:  nil,
		EndDate:    nil,
	}

	assert.NilError(t, s.stateStore.BatchTable().Insert(s.ctx, batch))

	res, err := s.k.Batches(s.ctx, &core.QueryBatchesRequest{
		ProjectId:  "C01-001",
		Pagination: &query.PageRequest{Limit: 1, CountTotal: true},
	})
```

Logs
```
--- FAIL: TestQuery_Batches (0.00s)
panic: iterator is invalid [recovered]
	panic: iterator is invalid

goroutine 37 [running]:
testing.tRunner.func1.2({0x11f1220, 0x16f67e0})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x11f1220, 0x16f67e0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/tendermint/tm-db.(*memDBIterator).assertIsValid(...)
	/home/user/go/pkg/mod/github.com/tendermint/tm-db@v0.6.7/memdb_iterator.go:155
github.com/tendermint/tm-db.(*memDBIterator).Next(0xc0004e6140?)
	/home/user/go/pkg/mod/github.com/tendermint/tm-db@v0.6.7/memdb_iterator.go:126 +0xa5
github.com/cosmos/cosmos-sdk/orm/model/ormtable.(*indexIterator).Next(0xc00111d480)
	/home/user/go/pkg/mod/github.com/cosmos/cosmos-sdk/orm@v1.0.0-alpha.11/model/ormtable/iterator.go:217 +0x38
github.com/cosmos/cosmos-sdk/orm/model/ormtable.(*paginationIterator).Next(0xc000e4fa10)
	/home/user/go/pkg/mod/github.com/cosmos/cosmos-sdk/orm@v1.0.0-alpha.11/model/ormtable/paginate.go:64 +0x171
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
Closed via #1344
